[sources.generate_syslog]
type = "demo_logs"
format = "syslog"
count = 100

[transforms.remap_syslog]
inputs = [ "generate_syslog"]
type = "remap"
source = '''
  structured = parse_syslog!(.message)
  . = merge(., structured)
'''

#inputs = ["remap_syslog"]
#type = "console"
#encoding.codec = "json"

[sinks.my_sink_id]
type = "clickhouse"
inputs = [ "remap_syslog" ]
database = "logs"
endpoint = "http://localhost:8123"
table = "mytable"
compression = "gzip"
