---
- name: Install Clickhouse
  hosts: clickhouse
  roles: 
    - clickhouse
- name: Install Lighthouse
  hosts: lighthouse
  roles: 
    - my_lighthouse
- name: Install Vector
  hosts: vector
  roles:
    - my_vector

